### ISSUE TITLE
Add to existing model

### ISSUE THREAD

**Issue by StefaanAvonds** [mobilemotion/SQLite.Net.DateTimeOffset#1]
Works great for new entries to the SQLite-database. However when adding a new property to an existing model using attribute [DateTimeOffsetSerialize], the existing entries won't have a value for the string-column thus generates an error for the DateTimeOffset-property.

Can the value for existing entries be set to DateTimeOffset.MinValue?

**Comment by mobilemotion** [comment]
Good point, didn't think about that. While defining a default value should be possible and would avoid null reference errors, I think the core problem is that the original DateTime value is lost. If you have an idea and the time to prototype a solution, feel free to open a pull request, otherwise I'll have a look at it as soon as I'm back in the office next week!

**Comment by mobilemotion** [comment]
Fixed in version 1.1.0 (available on NuGet): Using default(DateTimeOffset).ToString() as default value for the new property
