### ISSUE TITLE
is it possible to convert this to .netStandard 

### ISSUE THREAD

**Issue by JoacimWall** [mobilemotion/SQLite.Net.DateTimeOffset#3]

**Comment by mobilemotion** [comment]
Since this project consists of two libraries, there is no short answer:

- For `SQLite.Net.DateTimeOffset.Attributes` you are right, it would be good to have it as .NET Standard in case it needs to be referenced from some .NET Standard library. I'll have a look into this.

- The `SQLite.Net.DateTimeOffset.PostBuild` project heavily depends on the `Mono.Cecil` library which is not yet available for .NET Standard, so it won't be possible to convert this one at the moment. However, there is no point in doing so anyway, since this library won't be referenced by any .NET project (it will only be called by Visual Studio during compilation).

**Comment by mobilemotion** [comment]
Fixed in v 1.2.0. Please not that this version also switches from SQLite.Net-PCL to sqlite-net-pcl as underlying base SQL library, since only this one supports .NET Standard (and it is the recommended choice anyway, since SQLite.Net-PCL seems to be deprecated).
